### ISSUE TITLE
There is a lot of shit in tmp that should not be

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/dio-web#5]
@MakeilaLundy @JWTappert What is wrong with this commit:
https://github.com/osu-cascades/dio-web/commit/350c3aa0efb41c716c2f739940154940d56e9130

?

**Comment by JWTappert** [comment]
@ybakos Already have an issue opened for this

**Comment by ybakos** [comment]
@JWTappert I see it now. Try to link to related issues when you close a duplicate.
eg:
See https://github.com/osu-cascades/dio-web/issues/2
